from __future__ import annotations

EXTRACTION_ENTITY_TERMS: tuple[str, ...] = (
    "person",
    "crowd",
    "child",
    "runner",
    "walker",
    "dancer",
    "speaker",
    "singer",
    "fighter",
    "hand",
    "car",
    "truck",
    "bus",
    "train",
    "tram",
    "subway train",
    "motorcycle",
    "bicycle",
    "scooter",
    "skateboard",
    "boat",
    "ship",
    "airplane",
    "helicopter",
    "dog",
    "cat",
    "bird",
    "horse",
    "cow",
    "sheep",
    "goat",
    "ball",
    "bat",
    "racket",
    "paddle",
    "club",
    "sword",
    "stick",
    "drum",
    "cymbal",
    "guitar",
    "piano",
    "violin",
    "microphone",
    "speaker cabinet",
    "door",
    "drawer",
    "cabinet",
    "keyboard",
    "phone",
    "bottle",
    "glass",
    "plate",
    "cup",
    "table",
    "chair",
    "engine",
    "machine",
    "fan",
    "printer",
    "drill",
    "hammer",
    "saw",
    "firework",
    "waterfall",
    "wave",
    "rain",
    "fire",
    "object",
)

SEMANTIC_HINT_TERMS: tuple[str, ...] = (
    "metal",
    "wood",
    "glass",
    "plastic",
    "ceramic",
    "fabric",
    "paper",
    "stone",
    "gravel",
    "water",
    "rain",
    "smoke",
    "crowd scene",
    "street",
    "train station",
    "subway platform",
    "kitchen",
    "sports court",
    "stadium",
    "workshop",
    "office",
    "classroom",
    "wooden floor",
    "tile floor",
    "grass",
    "sand",
    "metal surface",
    "glass surface",
    "tabletop",
    "wall",
    "window",
    "doorway",
    "running",
    "marching",
    "clapping",
    "fighting",
    "swinging",
    "striking",
    "opening",
    "closing",
    "pouring",
    "riding",
    "driving",
    "waving water",
    "explosion burst",
    "continuous motion",
    "contact event",
    "ambience texture",
)

EMERGENCY_FALLBACK_PROMPTS: tuple[str, ...] = (
    "person",
    "vehicle",
    "animal",
    "object",
)
