from __future__ import annotations

from collections.abc import Iterable


def _normalized_unique(*groups: Iterable[str]) -> tuple[str, ...]:
    values: list[str] = []
    seen: set[str] = set()
    for group in groups:
        for item in group:
            normalized = item.strip().lower()
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            values.append(normalized)
    return tuple(values)


PEOPLE_ENTITY_TERMS: tuple[str, ...] = (
    "person",
    "people",
    "crowd",
    "audience",
    "spectator",
    "child",
    "children",
    "baby",
    "adult",
    "man",
    "woman",
    "boy",
    "girl",
    "runner",
    "walker",
    "jogger",
    "marcher",
    "dancer",
    "fighter",
    "athlete",
    "performer",
    "musician",
    "drummer",
    "guitarist",
    "singer",
    "speaker",
    "driver",
    "rider",
    "cyclist",
    "skater",
    "worker",
    "chef",
    "gamer",
    "crowd subgroup",
    "group of people",
    "hand",
    "hands",
    "foot",
    "feet",
    "shoe",
    "shoes",
)

VEHICLE_ENTITY_TERMS: tuple[str, ...] = (
    "vehicle",
    "car",
    "sedan",
    "hatchback",
    "truck",
    "pickup truck",
    "lorry",
    "bus",
    "school bus",
    "van",
    "taxi",
    "train",
    "freight train",
    "subway train",
    "metro train",
    "tram",
    "railcar",
    "locomotive",
    "motorcycle",
    "scooter",
    "moped",
    "bicycle",
    "bike",
    "skateboard",
    "roller skates",
    "boat",
    "ship",
    "ferry",
    "kayak",
    "canoe",
    "airplane",
    "jet",
    "helicopter",
    "drone",
    "engine",
    "car engine",
    "wheel",
    "tire",
    "rail track",
)

ANIMAL_ENTITY_TERMS: tuple[str, ...] = (
    "animal",
    "dog",
    "puppy",
    "cat",
    "kitten",
    "bird",
    "pigeon",
    "seagull",
    "duck",
    "goose",
    "chicken",
    "horse",
    "pony",
    "cow",
    "bull",
    "goat",
    "sheep",
    "pig",
    "elephant",
    "lion",
    "tiger",
    "bear",
    "monkey",
    "camel",
    "deer",
    "frog",
    "insect",
)

SPORT_CONTACT_TERMS: tuple[str, ...] = (
    "ball",
    "soccer ball",
    "basketball",
    "baseball",
    "tennis ball",
    "ping pong ball",
    "golf ball",
    "bat",
    "baseball bat",
    "racket",
    "tennis racket",
    "paddle",
    "table tennis paddle",
    "golf club",
    "hockey stick",
    "stick",
    "sword",
    "wooden sword",
    "foam sword",
    "club",
    "shield",
    "goal post",
    "net",
    "table tennis table",
    "tennis court",
    "sports table",
)

MUSIC_OBJECT_TERMS: tuple[str, ...] = (
    "instrument",
    "drum",
    "snare drum",
    "bass drum",
    "drum kit",
    "cymbal",
    "hi hat",
    "guitar",
    "acoustic guitar",
    "electric guitar",
    "piano",
    "keyboard instrument",
    "violin",
    "cello",
    "flute",
    "trumpet",
    "microphone",
    "speaker cabinet",
    "amp",
    "music stand",
)

HOUSEHOLD_INTERACTION_TERMS: tuple[str, ...] = (
    "door",
    "drawer",
    "cabinet",
    "cupboard",
    "closet",
    "window",
    "window blind",
    "keyboard",
    "computer keyboard",
    "mouse",
    "phone",
    "telephone",
    "remote control",
    "bottle",
    "glass",
    "cup",
    "mug",
    "plate",
    "dish",
    "bowl",
    "fork",
    "spoon",
    "knife",
    "pan",
    "pot",
    "kettle",
    "sink",
    "faucet",
    "table",
    "chair",
    "desk",
    "countertop",
    "refrigerator",
    "washing machine",
    "dishwasher",
    "vacuum cleaner",
    "toilet lid",
)

TOOLS_MACHINE_TERMS: tuple[str, ...] = (
    "machine",
    "fan",
    "ceiling fan",
    "printer",
    "drill",
    "hammer",
    "saw",
    "power tool",
    "generator",
    "compressor",
    "lawn mower",
    "chainsaw",
    "engine block",
    "excavator",
    "bulldozer",
    "forklift",
    "robot arm",
    "factory machine",
    "conveyor belt",
    "cash register",
)

NATURE_ENTITY_TERMS: tuple[str, ...] = (
    "waterfall",
    "wave",
    "ocean wave",
    "rain",
    "fire",
    "flame",
    "firework",
    "fountain",
    "river",
    "stream",
    "smoke plume",
    "tree branch",
    "leaves",
)

GENERIC_ENTITY_TERMS: tuple[str, ...] = (
    "object",
    "foreground object",
    "handheld object",
    "metal object",
    "wooden object",
    "glass object",
    "container",
    "tool",
)

EXTRACTION_ENTITY_TERMS: tuple[str, ...] = _normalized_unique(
    PEOPLE_ENTITY_TERMS,
    VEHICLE_ENTITY_TERMS,
    ANIMAL_ENTITY_TERMS,
    SPORT_CONTACT_TERMS,
    MUSIC_OBJECT_TERMS,
    HOUSEHOLD_INTERACTION_TERMS,
    TOOLS_MACHINE_TERMS,
    NATURE_ENTITY_TERMS,
    GENERIC_ENTITY_TERMS,
)

ENVIRONMENT_HINT_TERMS: tuple[str, ...] = (
    "street",
    "road",
    "crosswalk",
    "sidewalk",
    "parking lot",
    "train station",
    "subway platform",
    "rail corridor",
    "sports court",
    "stadium",
    "arena",
    "gym",
    "classroom",
    "office",
    "kitchen",
    "dining room",
    "bathroom",
    "bedroom",
    "living room",
    "workshop",
    "garage",
    "factory floor",
    "warehouse",
    "restaurant",
    "store",
    "market",
    "forest",
    "beach",
    "coast",
    "waterfront",
    "riverbank",
    "rainy street",
    "crowd scene",
    "performance stage",
    "construction site",
)

MATERIAL_HINT_TERMS: tuple[str, ...] = (
    "metal",
    "wood",
    "glass",
    "plastic",
    "rubber",
    "ceramic",
    "fabric",
    "paper",
    "stone",
    "gravel",
    "water",
    "sand",
    "grass",
    "concrete",
    "asphalt",
    "tile",
    "carpet",
    "wooden floor",
    "tile floor",
    "metal surface",
    "glass surface",
    "tabletop",
    "wall",
    "doorway",
    "window frame",
    "countertop",
)

ACTION_HINT_TERMS: tuple[str, ...] = (
    "running",
    "walking",
    "marching",
    "clapping",
    "fighting",
    "sparring",
    "swinging",
    "striking",
    "hitting",
    "kicking",
    "drumming",
    "playing instrument",
    "riding",
    "driving",
    "rolling",
    "sliding",
    "opening",
    "closing",
    "typing",
    "tapping",
    "pouring",
    "shaking",
    "explosion burst",
    "continuous motion",
    "contact event",
    "repeating impacts",
    "foreground interaction",
)

ROUTING_HINT_TERMS: tuple[str, ...] = (
    "ambience texture",
    "continuous vehicle motion",
    "foreground impact",
    "ground contact",
    "metallic impact",
    "wood impact",
    "glass rattle",
    "water texture",
    "crowd texture",
    "machine hum",
    "engine start",
    "contact rhythm",
    "bursty impact",
)

SEMANTIC_HINT_TERMS: tuple[str, ...] = _normalized_unique(
    ENVIRONMENT_HINT_TERMS,
    MATERIAL_HINT_TERMS,
    ACTION_HINT_TERMS,
    ROUTING_HINT_TERMS,
)

EMERGENCY_FALLBACK_PROMPTS: tuple[str, ...] = (
    "person",
    "vehicle",
    "animal",
    "object",
)
